### ISSUE TITLE
Interactive map of famous people of Ukraine

### ISSUE THREAD

**Issue by Symbian9** [Symbian9/awesome-maps-ukraine#5]
> [Interactive map of famous people of Ukraine](https://github.com/VolodymyrEnders/Interactive-map-of-famous-people-of-Ukraine) - Interactive map of famous people of Ukraine on ASP.NET for my diploma work

NOTE: Need check later

**Comment by DmitryIvanov92** [comment]
This repo is empty so, no doubt, you can close the issue
